-- =============================================================================
-- BOTA PIZZERIA - Supabase Storage Setup
-- =============================================================================
-- Questo script configura il bucket 'img-bota' su Supabase per l'upload
-- delle immagini dal pannello admin.
--
-- ISTRUZIONI:
-- 1. Vai su Supabase Dashboard → Storage
-- 2. Crea un nuovo bucket chiamato 'img-bota'
-- 3. Imposta come PUBLIC (molto importante!)
-- 4. Non serve eseguire questo script nel SQL Editor perché
--    Supabase gestisce automaticamente le policy per i bucket pubblici
--
-- NOTA: Se hai già creato il bucket come PUBLIC, gli upload funzionano
-- senza bisogno di policy SQL aggiuntive.
-- =============================================================================

-- Questo script non richiede l'esecuzione di SQL.
-- La configurazione avviene tramite Supabase Dashboard:
--
-- 1. Storage → New bucket → nome: img-bota
-- 2. Public bucket: ON
-- 3. L'upload pubblico è consentito automaticamente dai client Supabase
--    usando la chiave anon (anon key) quando il bucket è PUBLIC

-- =============================================================================
-- FINE SETUP
-- =============================================================================