import type { SiteConfig } from './types';

export const STORAGE_KEY = 'website-framework-config-v2';
export const SUBMISSIONS_KEY = 'website-framework-submissions-v1';
export const COOKIE_KEY = 'website-framework-cookie-consent-v1';

export const DEFAULT_CONFIG: SiteConfig = {
  version: 1,
  sections: [
    { id: 'announcement', enabled: true },
    { id: 'header', enabled: true },
    { id: 'hero', enabled: true },
    { id: 'features', enabled: true },
    { id: 'about', enabled: true },
    { id: 'products', enabled: true },
    { id: 'pricing', enabled: false },
    { id: 'testimonials', enabled: true },
    { id: 'faq', enabled: true },
    { id: 'orari', enabled: true },
    { id: 'galleria', enabled: true },
    { id: 'contact', enabled: true },
    { id: 'footer', enabled: true },
  ],
  theme: {
    mode: 'light',
    primary: '#b91c1c',
    secondary: '#f59e0b',
    background: '#fef7ed',
    accent: '#dc2626',
    text: '#1c1917',
    mutedText: '#78716c',
    card: '#ffffff',
    border: '#f3e8d3',
    fontPreset: 'playfair',
    baseFontSize: 16,
    radius: 'lg',
    shadow: 'md',
  },
  announcement: {
    text: '🍕 Pizza artigianale cotta nel forno a legna — aperto tutte le sere da martedì a domenica!',
    linkText: 'Scopri il menu',
    linkHref: '#products',
    bg: '#b91c1c',
    fg: '#ffffff',
  },
  header: {
    logoText: 'Bota',
    links: [
      { id: 'l1', label: 'Storia', href: '#about' },
      { id: 'l2', label: 'Menu', href: '#products' },
      { id: 'l3', label: 'Orari', href: '#orari' },
      { id: 'l4', label: 'Galleria', href: '#galleria' },
      { id: 'l5', label: 'Contatti', href: '#contact' },
    ],
    ctaText: 'Prenota un Tavolo',
    ctaHref: '#contact',
    sticky: true,
  },
  hero: {
    badge: '🍕 Pizzeria Ristorante — Fano',
    title: 'Bota: la vera pizza marchigiana',
    subtitle:
      'Dal cuore di Fano, portiamo in tavola la passione per la pizza artigianale. Impasto a lunga lievitazione, ingredienti del territorio e forno a legna per un\'esperienza autentica. Vieni a trovarci nel centro storico di Fano.',
    primaryCtaText: 'Prenota Ora',
    primaryCtaHref: '#contact',
    secondaryCtaText: 'Esplora il Menu',
    secondaryCtaHref: '#products',
    bgType: 'image',
    gradientFrom: '#b91c1c',
    gradientTo: '#f59e0b',
    imageUrl:
      'https://images.pexels.com/photos/1146704/pexels-photo-1146704.jpeg?auto=compress&cs=tinysrgb&w=1600',
    overlayOpacity: 45,
  },
  features: {
    heading: 'Perché scegliere Bota',
    subheading: 'Ogni dettaglio conta — dall\'impasto al forno.',
    columns: 3,
    cards: [
      {
        id: 'f1',
        icon: 'Flame',
        title: 'Forno a Legna',
        description: 'Le nostre pizze sono cotte nel forno a legna a 450°C, per una crosta croccante e un cuore morbido.',
        badge: 'Tradizione',
      },
      {
        id: 'f2',
        icon: 'Leaf',
        title: 'Ingredienti del Territorio',
        description: 'Utilizziamo farine selezionate, pomodoro San Marzano e prodotti a km zero dalle Marche.',
        badge: 'Km Zero',
      },
      {
        id: 'f3',
        icon: 'Clock',
        title: 'Lunga Lievitazione',
        description: 'Il nostro impasto riposa per 48 ore, garantendo una pizza leggera e digeribile.',
        badge: '48h',
      },
      {
        id: 'f4',
        icon: 'Users',
        title: 'Ristorante Accogliente',
        description: 'Un ambiente familiare e curato, perfetto per cene in famiglia o con amici.',
        badge: 'Famiglia',
      },
      {
        id: 'f5',
        icon: 'Wine',
        title: 'Cantina Marchigiana',
        description: 'Una selezione di vini locali: Verdicchio, Rosso Conero e spumanti delle Marche.',
        badge: 'Vini Locali',
      },
      {
        id: 'f6',
        icon: 'Heart',
        title: 'Passione dal 1995',
        description: 'Da oltre 25 anni portiamo avanti la tradizione della pizza marchigiana a Fano.',
        badge: 'Dal 1995',
      },
    ],
  },
  about: {
    heading: 'La nostra storia',
    body: 'Bota nasce a Fano nel 1995, nel cuore del centro storico, dalla passione di una famiglia per la vera pizza italiana. Da allora, portiamo avanti la tradizione con un impasto a lunga lievitazione, ingredienti selezionati e un forno a legna che regala alla nostra pizza quel sapore unico e inconfondibile. Oggi Bota è un punto di riferimento per gli amanti della buona cucina a Fano: non solo pizza, ma anche antipasti, primi piatti della tradizione marchigiana e dolci fatti in casa.',
    imageUrl:
      'https://images.pexels.com/photos/35518412/pexels-photo-35518412.jpeg?auto=compress&cs=tinysrgb&w=900',
    imageAlt: 'L\'accogliente sala interna del ristorante Bota a Fano',
    stats: [
      { id: 's1', value: '25+', label: 'Anni di Storia' },
      { id: 's2', value: '100k+', label: 'Pizze Sfornate' },
      { id: 's3', value: '50+', label: 'Varietà di Pizze' },
      { id: 's4', value: '4.8/5', label: 'Voto dei Clienti' },
    ],
  },
  products: {
    heading: 'Il Nostro Menu',
    subheading: 'Pizze classiche, specialità della casa e prelibatezze del territorio',
    layout: 'grid',
    columns: 3,
    categories: [
      {
        id: 'cat1',
        name: 'Pizze Classiche',
        description: 'Le pizze tradizionali che hanno fatto la storia',
        icon: 'Pizza',
      },
      {
        id: 'cat2',
        name: 'Specialità della Casa',
        description: 'Le nostre creazioni esclusive',
        icon: 'Star',
      },
      {
        id: 'cat3',
        name: 'Antipasti',
        description: 'Per iniziare la serata',
        icon: 'Utensils',
      },
      {
        id: 'cat4',
        name: 'Primi Piatti',
        description: 'La tradizione marchigiana',
        icon: 'Soup',
      },
      {
        id: 'cat5',
        name: 'Dolci',
        description: 'Fatti in casa con passione',
        icon: 'Cake',
      },
      {
        id: 'cat6',
        name: 'Bevande',
        description: 'Vini, birre e molto altro',
        icon: 'Wine',
      },
    ],
    products: [
      {
        id: 'pr1',
        name: 'Margherita',
        description: 'Pomodoro San Marzano, mozzarella fior di latte, basilico fresco, olio extravergine d\'oliva.',
        price: '€7,00',
        imageUrl: 'https://mthxayxywvyjrnvuqkow.supabase.co/storage/v1/object/public/img-bota/bota/images/Screenshot%202026-08-06%20162124.png',
        badge: 'Classica',
        features: ['Pomodoro San Marzano', 'Fior di latte', 'Basilico fresco', 'Olio EVO'],
        ingredients: 'Pomodoro San Marzano DOP, mozzarella fior di latte, basilico fresco, olio extravergine d\'oliva italiano.',
        allergens: 'Lattosio, glutine',
        buttonText: 'Ordina Ora',
        buttonHref: '#contact',
        categoryId: 'cat1',
        meal: 'both',
        dishType: 'pizza',
      },
      {
        id: 'pr2',
        name: 'Marinara',
        description: 'Pomodoro San Marzano, aglio, origano, olio extravergine d\'oliva. La più semplice e genuina.',
        price: '€6,00',
        imageUrl: 'https://mthxayxywvyjrnvuqkow.supabase.co/storage/v1/object/public/img-bota/bota/images/Screenshot%202026-08-06%20171543.png',
        badge: 'Tradizionale',
        features: ['Pomodoro San Marzano', 'Aglio', 'Origano', 'Olio EVO'],
        ingredients: 'Pomodoro San Marzano DOP, aglio fresco, origano, olio extravergine d\'oliva.',
        allergens: 'Glutine',
        buttonText: 'Ordina Ora',
        buttonHref: '#contact',
        categoryId: 'cat1',
        meal: 'both',
        dishType: 'pizza',
      },
      {
        id: 'pr3',
        name: 'Diavola',
        description: 'Pomodoro, mozzarella, salame piccante, olive nere. Per chi ama il gusto deciso.',
        price: '€9,00',
        imageUrl: 'https://mthxayxywvyjrnvuqkow.supabase.co/storage/v1/object/public/img-bota/bota/images/Screenshot%202026-08-08%20084127.png',
        badge: 'Piccante',
        features: ['Pomodoro', 'Fior di latte', 'Salame piccante', 'Olive nere'],
        ingredients: 'Pomodoro San Marzano, mozzarella fior di latte, salame piccante artigianale, olive nere denocciolate.',
        allergens: 'Lattosio, glutine, sedano',
        buttonText: 'Ordina Ora',
        buttonHref: '#contact',
        categoryId: 'cat2',
        meal: 'both',
        dishType: 'pizza',
      },
      {
        id: 'pr4',
        name: 'Bota Speciale',
        description: 'La nostra pizza signature: crema di tartufo, funghi porcini, prosciutto crudo e scaglie di parmigiano.',
        price: '€14,00',
        imageUrl: 'https://mthxayxywvyjrnvuqkow.supabase.co/storage/v1/object/public/img-bota/bota/images/Screenshot%202026-08-08%20084525.png',
        badge: 'Signature',
        features: ['Crema di tartufo', 'Funghi porcini', 'Prosciutto crudo', 'Parmigiano'],
        ingredients: 'Crema di tartufo, funghi porcini freschi, prosciutto crudo di Parma, scaglie di parmigiano 36 mesi, mozzarella.',
        allergens: 'Lattosio, glutine',
        buttonText: 'Ordina Ora',
        buttonHref: '#contact',
        categoryId: 'cat2',
        meal: 'both',
        dishType: 'pizza',
      },
      {
        id: 'pr5',
        name: 'Quattro Formaggi',
        description: 'Mozzarella, gorgonzola, taleggio e parmigiano su base di pomodoro e origano.',
        price: '€10,50',
        imageUrl: 'https://mthxayxywvyjrnvuqkow.supabase.co/storage/v1/object/public/img-bota/bota/images/Screenshot%202026-08-08%20084536.png',
        badge: 'Gourmet',
        features: ['Mozzarella', 'Gorgonzola', 'Taleggio', 'Parmigiano'],
        ingredients: 'Mozzarella, gorgonzola DOP, taleggio, parmigiano reggiano 24 mesi, pomodoro San Marzano.',
        allergens: 'Lattosio, glutine',
        buttonText: 'Ordina Ora',
        buttonHref: '#contact',
        categoryId: 'cat2',
        meal: 'both',
        dishType: 'pizza',
      },
      {
        id: 'pr6',
        name: 'Prosciutto e Rucola',
        description: 'Pomodoro, mozzarella, prosciutto crudo di Parma e rucola fresca. Un classico intramontabile.',
        price: '€11,00',
        imageUrl: 'https://mthxayxywvyjrnvuqkow.supabase.co/storage/v1/object/public/img-bota/bota/images/Screenshot%202026-08-08%20084542.png',
        badge: 'Classica',
        features: ['Pomodoro', 'Fior di latte', 'Prosciutto di Parma', 'Rucola fresca'],
        ingredients: 'Pomodoro San Marzano, mozzarella fior di latte, prosciutto crudo di Parma 18 mesi, rucola fresca.',
        allergens: 'Lattosio, glutine',
        buttonText: 'Ordina Ora',
        buttonHref: '#contact',
        categoryId: 'cat1',
        meal: 'both',
        dishType: 'pizza',
      },
      {
        id: 'pr7',
        name: 'Bruschetta al Pomodoro',
        description: 'Pane bruscato con pomodori freschi, aglio e basilico. Antipasto perfetto per iniziare.',
        price: '€6,50',
        imageUrl: 'https://mthxayxywvyjrnvuqkow.supabase.co/storage/v1/object/public/img-bota/bota/images/Screenshot%202026-08-08%20084553.png',
        badge: 'Vegetariano',
        features: ['Pomodori freschi', 'Aglio', 'Basilico', 'Olio EVO'],
        ingredients: 'Pane artigianale, pomodori San Marzano freschi, aglio fresco, basilico, olio extravergine d\'oliva.',
        allergens: 'Glutine',
        buttonText: 'Ordina Ora',
        buttonHref: '#contact',
        categoryId: 'cat3',
        meal: 'lunch',
        dishType: 'antipasto',
        availableDays: ['monday', 'tuesday', 'wednesday', 'thursday', 'friday'],
      },
      {
        id: 'pr8',
        name: 'Prosciutto e Melone',
        description: 'Prosciutto di Parma con melone fresco di stagione.',
        price: '€8,50',
        imageUrl: 'https://mthxayxywvyjrnvuqkow.supabase.co/storage/v1/object/public/img-bota/bota/images/Screenshot%202026-08-08%20084602.png',
        badge: 'Stagionale',
        features: ['Prosciutto di Parma', 'Melone fresco'],
        ingredients: 'Prosciutto di Parma 18 mesi, melone fresco di stagione.',
        allergens: 'Nessuno',
        buttonText: 'Ordina Ora',
        buttonHref: '#contact',
        categoryId: 'cat3',
        meal: 'lunch',
        dishType: 'antipasto',
        availableDays: ['monday', 'tuesday', 'wednesday'],
      },
      {
        id: 'pr9',
        name: 'Insalata di Polpo',
        description: 'Polpo tenero con patate, olive e pomodorini.',
        price: '€10,00',
        imageUrl: 'https://mthxayxywvyjrnvuqkow.supabase.co/storage/v1/object/public/img-bota/bota/images/Screenshot%202026-08-08%20084610.png',
        badge: 'Fresco',
        features: ['Polpo', 'Patate', 'Olive'],
        ingredients: 'Polpo mediterraneo, patate, olive taggiasche, pomodorini, prezzemolo, olio EVO.',
        allergens: 'Pesce',
        buttonText: 'Ordina Ora',
        buttonHref: '#contact',
        categoryId: 'cat3',
        meal: 'lunch',
        dishType: 'antipasto',
        availableDays: ['thursday', 'friday'],
      },
      {
        id: 'pr10',
        name: 'Risotto ai Funghi Porcini',
        description: 'Riso carnaroli, funghi porcini freschi, parmigiano reggiano e burro di malga.',
        price: '€12,00',
        imageUrl: 'https://mthxayxywvyjrnvuqkow.supabase.co/storage/v1/object/public/img-bota/bota/images/Screenshot%202026-08-08%20084627.png',
        badge: 'Chef',
        features: ['Riso Carnaroli', 'Funghi Porcini', 'Parmigiano', 'Burro di malga'],
        ingredients: 'Riso Carnaroli, funghi porcini freschi, parmigiano reggiano 24 mesi, burro di malga, cipolla dorata.',
        allergens: 'Lattosio',
        buttonText: 'Ordina Ora',
        buttonHref: '#contact',
        categoryId: 'cat4',
        meal: 'lunch',
        dishType: 'primo',
        availableDays: ['monday', 'tuesday', 'wednesday', 'thursday', 'friday'],
      },
      {
        id: 'pr11',
        name: 'Spaghetti alla Carbonara',
        description: 'La tradizione romana: guanciale, pecorino, tuorlo d\'uovo e pepe nero.',
        price: '€11,00',
        imageUrl: 'https://mthxayxywvyjrnvuqkow.supabase.co/storage/v1/object/public/img-bota/bota/images/Screenshot%202026-08-08%20084634.png',
        badge: 'Classica',
        features: ['Guanciale', 'Pecorino', 'Tuorlo d\'uovo'],
        ingredients: 'Spaghetti di grano duro, guanciale artigianale, pecorino romano DOP, tuorli d\'uovo freschi, pepe nero.',
        allergens: 'Glutine, Uova',
        buttonText: 'Ordina Ora',
        buttonHref: '#contact',
        categoryId: 'cat4',
        meal: 'lunch',
        dishType: 'primo',
        availableDays: ['monday', 'wednesday', 'friday'],
      },
      {
        id: 'pr12',
        name: 'Penne all\'Arrabbiata',
        description: 'Pomodoro, aglio, peperoncino e prezzemolo. Il primo piccante della tradizione.',
        price: '€9,00',
        imageUrl: 'https://images.pexels.com/photos/4518598/pexels-photo-4518598.jpeg?auto=compress&cs=tinysrgb&w=400',
        badge: 'Piccante',
        features: ['Pomodoro', 'Peperoncino', 'Aglio'],
        ingredients: 'Penne di grano duro, pomodoro San Marzano, aglio fresco, peperoncino calabrese, prezzemolo, olio EVO.',
        allergens: 'Glutine',
        buttonText: 'Ordina Ora',
        buttonHref: '#contact',
        categoryId: 'cat4',
        meal: 'lunch',
        dishType: 'primo',
        availableDays: ['tuesday', 'thursday'],
      },
      {
        id: 'pr13',
        name: 'Patate al Forno',
        description: 'Patate arrosto con rosmarino e aglio.',
        price: '€4,00',
        imageUrl: 'https://mthxayxywvyjrnvuqkow.supabase.co/storage/v1/object/public/img-bota/bota/images/Screenshot%202026-08-08%20084657.png',
        badge: 'Classico',
        features: ['Patate', 'Rosmarino'],
        ingredients: 'Patate fresche, rosmarino, aglio, olio EVO, sale marino.',
        allergens: 'Nessuno',
        buttonText: 'Ordina Ora',
        buttonHref: '#contact',
        categoryId: 'cat7',
        meal: 'lunch',
        dishType: 'contorno',
        availableDays: ['monday', 'tuesday', 'wednesday', 'thursday', 'friday'],
      },
      {
        id: 'pr14',
        name: 'Verdure Grigliate',
        description: 'Zucchine, melanzane e peperoni grigliati.',
        price: '€5,00',
        imageUrl: 'https://mthxayxywvyjrnvuqkow.supabase.co/storage/v1/object/public/img-bota/bota/images/Screenshot%202026-08-08%20084712.png',
        badge: 'Vegetariano',
        features: ['Zucchine', 'Melanzane', 'Peperoni'],
        ingredients: 'Zucchine, melanzane, peperoni, olio EVO, erbe aromatiche.',
        allergens: 'Nessuno',
        buttonText: 'Ordina Ora',
        buttonHref: '#contact',
        categoryId: 'cat7',
        meal: 'lunch',
        dishType: 'contorno',
        availableDays: ['monday', 'wednesday', 'friday'],
      },
      {
        id: 'pr15',
        name: 'Insalata Mista',
        description: 'Lattuga, pomodorini, carote, mais e olive.',
        price: '€4,50',
        imageUrl: 'https://images.pexels.com/photos/4110015/pexels-photo-4110015.jpeg?auto=compress&cs=tinysrgb&w=400',
        badge: 'Fresca',
        features: ['Lattuga', 'Pomodorini', 'Olive'],
        ingredients: 'Lattuga, pomodorini, carote, mais, olive, cipolla rossa, olio EVO, aceto balsamico.',
        allergens: 'Nessuno',
        buttonText: 'Ordina Ora',
        buttonHref: '#contact',
        categoryId: 'cat7',
        meal: 'lunch',
        dishType: 'contorno',
        availableDays: ['tuesday', 'thursday'],
      },
      {
        id: 'pr16',
        name: 'Tiramisù Classico',
        description: 'Mascarpone, caffè espresso, savoiardi e cacao amaro. Il dolce italiano per eccellenza.',
        price: '€7,00',
        imageUrl: 'https://mthxayxywvyjrnvuqkow.supabase.co/storage/v1/object/public/img-bota/bota/images/Screenshot%202026-08-08%20084724.png',
        badge: 'Fatto in Casa',
        features: ['Mascarpone', 'Caffè espresso', 'Savoiardi', 'Cacao'],
        ingredients: 'Mascarpone fresco, caffè espresso, savoiardi, uova fresche, zucchero, cacao amaro.',
        allergens: 'Glutine, lattosio, uova',
        buttonText: 'Ordina Ora',
        buttonHref: '#contact',
        categoryId: 'cat5',
        meal: 'both',
        dishType: 'dolce',
      },
      {
        id: 'pr17',
        name: 'Vino Verdicchio DOC',
        description: 'Vino bianco marchigiano, secco e aromatico. Perfetto con pesce e antipasti.',
        price: '€18,00',
        imageUrl: 'https://mthxayxywvyjrnvuqkow.supabase.co/storage/v1/object/public/img-bota/bota/images/Screenshot%202026-08-08%20084738.png',
        badge: 'DOP',
        features: ['Verdicchio DOC', 'Marchigiano', 'Secco', '8° alcol'],
        ingredients: 'Vino Verdicchio dei Castelli di Jesi DOC, 12% vol, servito a 8-10°C.',
        allergens: 'Solfiti',
        buttonText: 'Ordina Ora',
        buttonHref: '#contact',
        categoryId: 'cat6',
        meal: 'both',
        dishType: 'bevanda',
      },
    ],
  },
  pricing: {
    heading: 'Menu Degustazione',
    subheading: 'I nostri percorsi gastronomici per vivere Bota al meglio',
    plans: [
      {
        id: 'p1',
        name: 'Pranzo',
        monthlyPrice: '€25',
        yearlyPrice: '€250',
        description: 'Antipasto, pizza, dolce e bevanda. Il menu perfetto per la pausa pranzo.',
        features: ['Antipasto del giorno', 'Pizza classica', 'Dolce della casa', 'Bevanda inclusa'],
        buttonText: 'Prenota',
        buttonHref: '#contact',
        popular: false,
      },
      {
        id: 'p2',
        name: 'Cena Completa',
        monthlyPrice: '€45',
        yearlyPrice: '€450',
        description: 'Il percorso completo: antipasti, primo, pizza, dolce e vino delle Marche.',
        features: [
          'Antipasti di mare e terra',
          'Primo della tradizione',
          'Pizza specialità della casa',
          'Dolce artigianale',
          'Vino locale incluso',
        ],
        buttonText: 'Prenota',
        buttonHref: '#contact',
        popular: true,
      },
      {
        id: 'p3',
        name: 'Degustazione Gourmet',
        monthlyPrice: '€60',
        yearlyPrice: '€600',
        description: 'Un\'esperienza culinaria completa con le nostre pizze gourmet più esclusive.',
        features: [
          'Pizza signature Bota',
          'Selezione di formaggi',
          'Tagliere di salumi',
          'Dolce del pasticcere',
          'Amaro o digestivo offerto',
        ],
        buttonText: 'Prenota',
        buttonHref: '#contact',
        popular: false,
      },
    ],
  },
  testimonials: {
    heading: 'Cosa dicono i nostri clienti',
    subheading: 'Le recensioni di chi ha già vissuto l\'esperienza Bota.',
    layout: 'grid',
    items: [
      {
        id: 't1',
        name: 'Marco R.',
        role: 'Cliente abituale',
        avatar: 'https://i.pravatar.cc/200?u=marco',
        rating: 5,
        text: 'La migliore pizza di Fano! L\'impasto è leggero e digeribile, cotto nel forno a legna alla perfezione. La Bota Speciale con tartufo è semplicemente eccezionale.',
      },
      {
        id: 't2',
        name: 'Giulia B.',
        role: 'Turista',
        avatar: 'https://i.pravatar.cc/200?u=giulia',
        rating: 5,
        text: 'Abbiamo scoperto Bota durante una vacanza a Fano. Ambiente accogliente, personale gentile e una pizza che non dimenticheremo. Torneremo sicuramente!',
      },
      {
        id: 't3',
        name: 'Alessandro C.',
        role: 'Critico gastronomico',
        avatar: 'https://i.pravatar.cc/200?u=alessandro',
        rating: 5,
        text: 'Un\'autentica pizzeria marchigiana. La lievitazione è perfetta, la scelta degli ingredienti è curata e la cantina offre ottimi vini locali. Consigliatissima.',
      },
      {
        id: 't4',
        name: 'Sara M.',
        role: 'Recensora Google',
        avatar: 'https://i.pravatar.cc/200?u=sara',
        rating: 4,
        text: 'Pizza ottima e servizio veloce. Il locale è carino anche se un po\' piccolo nei weekend. La quattro formaggi è da provare!',
      },
    ],
  },
  faq: {
    heading: 'Domande frequenti',
    subheading: 'Tutto quello che devi sapere su Bota.',
    items: [
      {
        id: 'q1',
        category: 'Prenotazioni',
        question: 'Come posso prenotare un tavolo?',
        answer:
          'Puoi prenotare chiamando direttamente il ristorante al numero 0721 000000, oppure compilando il modulo di contatto nella sezione Contatti. Per i weekend consigliamo di prenotare con qualche giorno di anticipo.',
      },
      {
        id: 'q2',
        category: 'Menu',
        question: 'Fate pizze senza glutine?',
        answer:
          'Sì, offriamo pizze senza glutine con impasto dedicato preparato in un\'area separata per evitare contaminazioni. Il supplemento è di €2,50.',
      },
      {
        id: 'q3',
        category: 'Menu',
        question: 'Avete opzioni vegetariane e vegane?',
        answer:
          'Assolutamente sì! Abbiamo diverse pizze vegetariane e possiamo preparare versioni vegane con formaggio vegetale su richiesta. Il nostro menù è pensato per tutti i gusti.',
      },
      {
        id: 'q4',
        category: 'Ristorante',
        question: 'Fate anche asporto e consegna a domicilio?',
        answer:
          'Sì, puoi ordinare da asporto chiamando il ristorante. La consegna a domicilio è disponibile nel centro di Fano e nelle zone limitrofe, dal martedì alla domenica dalle 18:30.',
      },
      {
        id: 'q5',
        category: 'Ristorante',
        question: 'Quali sono gli orari di apertura?',
        answer:
          'Siamo aperti dal martedì alla domenica, dalle 18:30 alle 23:00. Il lunedì il ristorante è chiuso. A pranzo siamo aperti il sabato e la domenica dalle 12:30 alle 14:30.',
      },
    ],
  },
  orari: {
    heading: 'Orari di Apertura',
    subheading: 'Vieni a trovarci — ti aspettiamo!',
    items: [
      { id: 'o1', day: 'Lunedì', lunch: 'Chiuso', dinner: 'Chiuso', closed: true },
      { id: 'o2', day: 'Martedì', lunch: 'Chiuso', dinner: '18:30 – 23:00', closed: false },
      { id: 'o3', day: 'Mercoledì', lunch: 'Chiuso', dinner: '18:30 – 23:00', closed: false },
      { id: 'o4', day: 'Giovedì', lunch: 'Chiuso', dinner: '18:30 – 23:00', closed: false },
      { id: 'o5', day: 'Venerdì', lunch: 'Chiuso', dinner: '18:30 – 23:00', closed: false },
      { id: 'o6', day: 'Sabato', lunch: '12:30 – 14:30', dinner: '18:30 – 23:00', closed: false },
      { id: 'o7', day: 'Domenica', lunch: '12:30 – 14:30', dinner: '18:30 – 23:00', closed: false },
    ],
    note: 'La cucina chiude 30 minuti prima dell\'orario indicato. Per il weekend consigliamo la prenotazione.',
  },
  galleria: {
    heading: 'La Nostra Galleria',
    subheading: 'Uno sguardo alla nostra cucina e ai nostri piatti',
    images: [
      {
        id: 'g1',
        src: 'https://images.pexels.com/photos/1146704/pexels-photo-1146704.jpeg?auto=compress&cs=tinysrgb&w=800',
        alt: 'Pizza nel forno a legna',
        caption: 'Il nostro forno a legna',
      },
      {
        id: 'g2',
        src: 'https://images.pexels.com/photos/275345/pexels-photo-275345.jpeg?auto=compress&cs=tinysrgb&w=800',
        alt: 'Pizza Margherita',
        caption: 'La nostra Margherita',
      },
      {
        id: 'g3',
        src: 'https://images.pexels.com/photos/158491/food-italian-cooking-pizza-158491.jpeg?auto=compress&cs=tinysrgb&w=800',
        alt: 'Ingredienti freschi',
        caption: 'Ingredienti del territorio',
      },
      {
        id: 'g4',
        src: 'https://images.pexels.com/photos/905847/pexels-photo-905847.jpeg?auto=compress&cs=tinysrgb&w=800',
        alt: 'Pizza gourmet con tartufo',
        caption: 'Bota Speciale al tartufo',
      },
      {
        id: 'g5',
        src: 'https://images.pexels.com/photos/1245449/pexels-photo-1245449.jpeg?auto=compress&cs=tinysrgb&w=800',
        alt: 'Pizza in forno',
        caption: 'Cottura a 450°C',
      },
      {
        id: 'g6',
        src: 'https://images.pexels.com/photos/2085949/pexels-photo-2085949.jpeg?auto=compress&cs=tinysrgb&w=800',
        alt: 'Pizza servita al tavolo',
        caption: 'Servita al tavolo',
      },
    ],
  },
  contact: {
    heading: 'Prenota il tuo tavolo',
    subheading: 'Hai domande, vuoi prenotare o organizzare un evento? Scrivici e ti risponderemo al più presto.',
    buttonText: 'Invia Richiesta',
    successMessage: 'Grazie per averci contattato! Ti risponderemo entro 24 ore.',
    fields: [
      { id: 'cf1', type: 'text', label: 'Nome e Cognome', placeholder: 'Mario Rossi', required: true, options: [] },
      { id: 'cf2', type: 'email', label: 'Indirizzo Email', placeholder: 'mario@esempio.com', required: true, options: [] },
      { id: 'cf3', type: 'phone', label: 'Numero di Telefono', placeholder: '+39 333 123 4567', required: true, options: [] },
      {
        id: 'cf4',
        type: 'select',
        label: 'Tipo di richiesta',
        placeholder: 'Seleziona un\'opzione',
        required: false,
        options: ['Prenotazione tavolo', 'Asporto', 'Eventi privati', 'Informazioni generali', 'Altro'],
      },
      {
        id: 'cf5',
        type: 'textarea',
        label: 'Il tuo messaggio',
        placeholder: 'Numero di persone, data, ora e qualsiasi richiesta speciale...',
        required: true,
        options: [],
      },
    ],
  },
  footer: {
    logoText: 'Bota',
    description: 'Pizzeria Ristorante nel cuore di Fano. Pizza artigianale cotta nel forno a legna, cucina marchigiana e vini del territorio. Dal 1995.',
    columns: [
      {
        id: 'fc1',
        title: 'Menu',
        links: [
          { id: 'fl1', label: 'Le Nostre Pizze', href: '#products' },
          { id: 'fl2', label: 'Chi Siamo', href: '#about' },
          { id: 'fl3', label: 'FAQ', href: '#faq' },
        ],
      },
      {
        id: 'fc2',
        title: 'Contatti',
        links: [
          { id: 'fl4', label: 'Prenota un Tavolo', href: '#contact' },
          { id: 'fl5', label: 'Tel: 0721 000000', href: 'tel:+390721000000' },
          { id: 'fl6', label: 'info@botafano.it', href: 'mailto:info@botafano.it' },
        ],
      },
      {
        id: 'fc3',
        title: 'Dove Siamo',
        links: [
          { id: 'fl7', label: 'Via Arco d\'Augusto, 12', href: 'https://maps.google.com/?q=Via+Arco+d\'Augusto+12+Fano' },
          { id: 'fl8', label: '61032 Fano (PU)', href: 'https://maps.google.com/?q=Fano+PU' },
          { id: 'fl9', label: 'Marche, Italia', href: 'https://maps.google.com/?q=Fano+PU' },
        ],
      },
    ],
    socials: [
      { id: 'so1', icon: 'Instagram', href: 'https://instagram.com/botafano' },
      { id: 'so2', icon: 'Facebook', href: 'https://facebook.com/botafano' },
      { id: 'so3', icon: 'Twitter', href: '#' },
      { id: 'so4', icon: 'Youtube', href: '#' },
    ],
    copyright: '© 2024 Bota Pizzeria Ristorante — Fano. Tutti i diritti riservati.',
    showLegalDisclaimer: false,
    legalText: '',
  },
  whatsapp: {
    enabled: true,
    phone: '393331234567',
    message: 'Ciao Bota! Vorrei prenotare un tavolo.',
  },
  cookie: {
    enabled: true,
    message: 'Utilizziamo i cookie per migliorare la tua esperienza di navigazione. Continuando a visitare il sito accetti l\'utilizzo dei cookie.',
    acceptText: 'Accetta',
    declineText: 'Rifiuta',
  },
  seo: {
    pageTitle: 'Bota — Pizzeria Ristorante a Fano | Pizza Artigianale',
    metaDescription: 'Bota è la pizzeria ristorante di Fano. Pizza artigianale cotta nel forno a legna, cucina marchigiana, vini del territorio. Prenota ora nel centro storico di Fano.',
    ogImageUrl: '',
  },
  code: {
    googleAnalyticsId: '',
    customHeadScripts: '',
    customBodyScripts: '',
  },
};